### ISSUE TITLE
npm dependencies

### ISSUE THREAD

**Issue by chadoh** [picnicss/picnic#102]
Hello! I love Picnic, awesome work.

For https://entire.life I use Picnic via npm. I just tried updating from 4.x to the latest 6.x, but when I pushed to Heroku got this error:

```npm ERR! enoent ENOENT: no such file or directory, rename '/tmp/build_99ffda271b8609ffec52546219a77370/node_modules/pangyp/nod
e_modules/async' -> '/tmp/build_99ffda271b8609ffec52546219a77370/node_modules/grunt-contrib-sass/node_modules/async'```

I haven't had time to dig in too deeply, but the error is coming from the `grunt-contrib-sass` dependency in picnic. I noticed that `grunt-contrib-sass` is both a regular dependency and a devDependency. Does it need to be both?

I tried reproducing the error by creating a new project with only picnic as a dependency, but that worked. So the issue seems to be that `grunt-contrib-sass` and some other package I'm installing use different `async` libraries, perhaps?

If the dependencies of picnic are really just devDependencies and they could be moved there, that would fix my problems! I'm not sure why picnic would need actual dependencies, since I think it just serves static assets. But I don't know much about it. 😄

**Comment by franciscop** [comment]
Yeah, it should be just devDependencies, I'll fix it ASAP

**Comment by emzo** [comment]
In fact, shouldn't all the packages listed as [dependencies](https://github.com/picnicss/picnic/blob/master/package.json#L37-L40) rather be devDependencies?

Since the [primary entry point](https://github.com/picnicss/picnic/blob/master/package.json#L11) is just a compiled CSS file, as a user of Picnic CSS, I don't think I need `grunt-bytesize`, `grunt-contrib-copy`, `grunt-contrib-sass` and `marked` installed on my system to use it.

**Comment by franciscop** [comment]
Fixed :)

**Comment by chadoh** [comment]
Thanks @franciscop! I am now using the nice new checkboxes on https://entire.life!
