### ISSUE TITLE
Typos and grammar issues on website

### ISSUE THREAD

**Issue by brendacs** [picnicss/picnic#126]
I was reading about Picnic on the website at [http://picnicss.com/](http://picnicss.com/) and I noticed there are a lot of minor grammar issues and no space before "terms and condition" (see screenshot below). It's just little things, but I think presentation matters.

![image](https://cloud.githubusercontent.com/assets/18357096/21494183/7ecec61e-cbc4-11e6-8bad-ab29a9c1bb9e.png)

I'd love to help fix these little issues since I'm just starting to try my hand at contributing to open source projects; I think these little things are a good place for me to start, and I'm very interested in this project!

**Comment by franciscop** [comment]
Sure! I think spacing issues come from migrating to Jade and then Pug (did I migrate to Pug?) and my editor.

**Comment by brendacs** [comment]
I see what you mean about the spacing issue.

Also, some fixes to grammar seem to have been made three days ago, but they just don't appear on the website because they haven't been migrated to the index.html. How would we do this (or would you handle it later on)?

**Comment by franciscop** [comment]
For minor fixes (missing an `'s`) I would just wait until the next small update, but since you batched few of them I just recompiled it and updated it.

If you want to go that extra step, you'd need to run `grunt` and it will create the proper HTML. Then I still need to pull from here and push to two Github Repositories (two different PR's to each wouldn't work).

Thank you for the fixes!

**Comment by brendacs** [comment]
Ah, I see. Thank you for explaining and no problem!
