### ISSUE TITLE
Keep up with bower

### ISSUE THREAD

**Issue by FranciscoP** [picnicss/picnic#34]
Until recently, I didn't fully grasp on what Bower was and how useful it is. But now that I understand that it's the `npm` of front-end, it's time to keep it updated.

**Comment by abuiles** [comment]
Hola @FranciscoP,

I'd like to give you a hand with this and get a proper release model through bower, currently, I'm not able to lock down to a given version since the assets since to be changing names, for example I was relying in bower_components/picnic/releases/v2.min.css but it disappeared.

Ideally people should be able to do `"picnic": "3.1.0",` in their bower and get the right version, also take advantage of semantic versioning.

How should the release work? 

Keep only 2 files in the directory releases: picnic.css and picnic.min.css and then use git to distribute the right version via bower.

Current bower version says "3.1.0" but if I try to install it via bower it won't work. If you are releasing version 3.1, then 1. create release files, commit and then `git tag 3.1.0` and `git push --tags`.


If a bug is fixed, then release 3.1.1, tag it as such and push. Always using the same name so the build tools pick the right version automatically.

**Comment by FranciscoP** [comment]
I see, I though I had to add a version in /releases (like /releases/v3.1.min.css) each time that I released a new version, which seemed really cumbersome (as I would need to update it in several places). With git tags it looks much easier.

Thank you for all the info and help, I will get down to it now.

**Comment by abuiles** [comment]
@FranciscoP awesome! Don't forget to push your tags. Also have you seen  http://semver.org/ ?

**Comment by FranciscoP** [comment]
I am trying to follow semver with Picnic CSS but it's daunting. In other lenguages like javascript where there's little public "surface" (only the public functions) and thus any "major" change is easily understood: a change in function name, a change in the arguments the function accepts, etc.

However for CSS it is difficult to say what "breaking compability" truly means as any small change modifies the style of the elements. Apparently I'm not [the first one who thinks this](https://twitter.com/markdalgleish/status/517214317574246400) and here's a more [in-depth, rant-ish public comment](https://gist.github.com/jashkenas/cbd2b088e20279ae2c8e).

Furthermore, now that I have different *plugins*, should I update the major version every time a small change happens in each plugin? While the answer is yes using semver, I think that's just a bit crazy... (note the attempted bump to 3.1 when I added a the class `.pseudo` to the plugin *button*).

**Comment by FranciscoP** [comment]
Tagged as bug since it was a bug for bower users.

Apparently I've managed to make it work. In a new project, with just `bower install picnic` I got it into `bower_components/picnic`, and the files are in:
-  `bower_components/picnic/releases/picnic.css`
-  `bower_components/picnic/releases/picnic.min.css`

Which I think is the purpose of bower. Then you should be able to use grunt or some other tool to include them, but that's outside the scope of Picnic, right?

**Comment by abuiles** [comment]
@FranciscoP correct :), just this is perfect, thanks!
