### ISSUE TITLE
menu not working with 3.4.2 on CDN

### ISSUE THREAD

**Issue by benkonrath** [picnicss/picnic#44]
Thanks for your work on this - I'm excited to get my site up and running using it.

I played around today and I couldn't get the menu to work with version 3.4.2 that's on the CDN:

```
<link href="//cdn.jsdelivr.net/picnicss/3.4.2/picnic.min.css" rel="stylesheet">
```

I tried with the css that the website is using (`www.picnicss.com/releases/plugins.min.css`) and it seemed to work. Browsing the history, I noticed that there was a commit to fix the nav recently (aa4f93a096ba6e086787c7a424e840ecc28cf565). Any idea what's going on? Has this fix been released already?

I also noticed that I get strange message when I do `bower install picnic`.

```
bower picnic#*                mismatch Version declared in the json (3.4.1) is different than the resolved one (3.4.2)
```
Could this be somehow related?

**Comment by franciscop** [comment]
Thanks for the report, I will try to explain this better in the homepage and documentation. But basically the `nav` is not one of the default plugins. To use it you can do two different things:

- Include the file `plugins.min.css` from [the CDN jsdelivr](http://www.jsdelivr.com/#!picnicss) which has all of the plugins.
- Use bower to get the sass [as explained in the documentation that I am writing](https://github.com/picnicss/picnic/blob/dev/documentation.md) (please note that this is for the upcoming 4.x and it's still not final).

About the bower message, I have no idea why it happens, it's stated in both the `package.json` and `bower.json` the version `3.4.2`. I will investigate this further.

**Comment by franciscop** [comment]
The commit you reference was about a problem in OS X and the build system. Also please note that the url you referenced `www.picnicss.com/releases/plugins.min.css` is being be deprecated in 4.x.

**Comment by benkonrath** [comment]
Thanks for looking into this.

I made a mistake in my report, I was actually including the plugins css. Try saving this html page and loading it in a browser. The nav snippet is from http://www.picnicss.com/plugins/nav/.

```html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Picnic CSS</title>
    <link href="https://cdn.jsdelivr.net/picnicss/3.4.2/plugins.min.css" rel="stylesheet">
</head>
<body>
<nav class="demo">
    <a href="#" class="brand">
        <span>Picnic CSS</span>
    </a>

    <!-- responsive-->
    <input id="bmenub" type="checkbox" class="show">
    <label for="bmenub" class="burger pseudo button">menu</label>

    <div class="menu">
        <a href="#" class="pseudo button icon-picture">Demo</a>
        <a href="#" class="button icon-puzzle">Plugins</a>
    </div>
</nav>
</body>
</html>
```

**Comment by franciscop** [comment]
You are completely right, I've been working now for a while and completely missed that in Picnic 3.x there was no `plugins.css`, [I proposed and made it for 4.0](https://github.com/picnicss/picnic/issues/39). The [file and html you named is completely broken](jsfiddle.net/franciscop/4tj30jgL/).

I made a temporary version, which stayed in `/releases/plugins.css` and was not supposed to be used. However, the people in jsdelivr probably saw that and included it, which would be perfect if it wasn't for it not being ready.

What do I propose to you?
- Grab a [copy from the latest dev copy](https://github.com/picnicss/picnic/tree/dev/releases). However, bear in mind that something might still change before the release.
- Use the current (but soon to be deleted) build system to also grab the nav: [http://www.picnicss.com/nut/picnic_3_4+nav.min.css](http://www.picnicss.com/nut/picnic_3_4+nav.min.css). Copy it locally since it'll be gone soon.

**Comment by jimaek** [comment]
@franciscop Your project is updated automatically by out bot, you tagged a new version and the bot picked it up https://github.com/jsdelivr/jsdelivr/pull/4858

Let me know what we can do to fix this issue

**Comment by franciscop** [comment]
@jimaek I think the best would be to wait to 4.0 and to delete the old (3.x) versions of **plugins.css** from the CDN. So I think the best is to wait for few days until 4.0 is released and then you can delete the 3.x, instead of cancelling it now and then having to add it in 4.0 since it'll be probably less work for you. Does that sound okay?

**Comment by benkonrath** [comment]
@franciscop Thanks for your help. I'm looking forward to trying 4.0 when its released.

**Comment by jimaek** [comment]
@franciscop Sorry but I cant delete anything. There are people that use it and their websites will break. People trust us that we wont modify or delete the files we host. I think simply hosting the latest version will be enough

**Comment by franciscop** [comment]
@jimaek that is true, however few (if any) people should be using it, since it's broken. I'll delete the link to that part from the current homepage though.
