### ISSUE TITLE
Picnic 4.0 is [almost] ready! Bugs?

### ISSUE THREAD

**Issue by franciscop** [picnicss/picnic#46]
The latest version is live in [**Picnic Test Website**](http://picnictest.herokuapp.com/). I am testing it and it works great in these versions:

- **IE 9**: Windows 7 compatibility view. Degrades gracefully.
- **IE 11**: Windows 7
- **Firefox**: Windows 7, OS X 10.9, Ubuntu 15.04, Android 5.0
- **Chrome**: Windows 7, Ubuntu 15.04, Android 5.0
- **Safari**: OS X 10.9

To test it in other device/platform, please refer to the [**test page**](http://picnictest.herokuapp.com/test) and play around with all the plugins until you break some (then report it please).

Edit: the IE I tested is IE 11, and later IE9 compatibility view

**Comment by benkonrath** [comment]
Are you planning to drop IE 9 support? I'm just wondering if I should test on IE 9 / Windows 7 with modern.ie.

**Comment by franciscop** [comment]
That's a great question. While [their share is dropping, it is still 3.5%](http://gs.statcounter.com/#desktop+mobile+tablet-browser_version_partially_combined-ww-monthly-201405-201505), for IE8 and IE9 combined. So my view is that it should at least degrade gracefully, which it does in the compatibility view for IE9 in IE 11. But if you can test it in real IE9 please do so, it's always better than the compatibility view.

**Comment by benkonrath** [comment]
I checked out the test page in IE 9 on Windows 7 with a VM image from modern.ie. Here's the problems I found:
* The tabs didn't work at all - only the first tab showed correctly. The second and third tabs showed cut off parts of the content from the first tab. 
* The grid also had some problems - it didn't expand to the full width of the main content area.

I'm personally ok if picnic targets IE 10+ as it's good for my needs. It's nice to have an official target so that I can inform users of older browsers that they should upgrade to get a better experience. Thanks.

**Comment by franciscop** [comment]
Okay, I confirm that in compatibility view I cannot still see the bugs. While the tabs would be forgivable with a proper note in the description of the plugin, the grid one is not okay since it's part of the core. However the grid wasn't changed from 3.x to 4.0, so the problem should be there now also.

Okay, let's do a IE 10+, the usage for IE 9 is quite low and dropping fast. I am going to release it now, thanks for all the help!
