### ISSUE TITLE
Should we add layouts?

### ISSUE THREAD

**Issue by franciscop** [picnicss/picnic#50]
While right now I don't have much time, I wonder what's the next thing to include in Picnic. Now I'm using it within many projects and I start to see new patterns. There is one thing that I keep repeating: layouts.

Be it a `hero` introduction, a Table of Contents, a Features section or other parts, these things keep popping up constantly. Arguably, `nav` and `footer` are also layouts. But what is a layout? How is it different from a plugin?

A layout is a structural part of a website that can contain a variety of other elements. An element is an independent, primary component. But some times it's difficult to tell them apart; is `card` a plugin or a layout? (maybe it's both so it might need to be split)

So, should we add more layouts?

**Comment by ramijarrar** [comment]
There are many other CSS libraries (Bootstrap, Min, Pure, Foundation, Semantic UI etc.) with diverse principles that already do a good job of providing a comprehensive set of well-built ‘layouts’, so I think it would be a shame to see Picnic attempt to replicate their work by moving in that direction.

What I would instead suggest is that the library make more of an effort to capitalise on the unique value it has over other libraries right now and this is in the approach it takes to styling elements that works with as opposed to sidestepping semantic HTML (i.e the beautiful ``<select>`` or ``<button>`` right out of the box) 

What I would imagine this involving for a future release of Picnic is a complete refactoring of the library to move ‘layouts’ out of core, so that it can be advertised as something new, like another layer on top of normalize.css that would provide a better set of defaults for libraries and apps. The current ‘layouts’ could then be made into a new library built upon Picnic that could embrace existing CSS libraries.

Any thoughts?

Side note: Your use of the word layout is confusing to developers who are using the SMACSS architecture (see [layout rules](https://smacss.com/book/type-layout)), I’d suggest a more neutral word like component or module (likewise for plugins, I would just call them elements to avoid creating new definitions)
