### ISSUE TITLE
Button's down state doesn't work when tapping trackpad on OS X

### ISSUE THREAD

**Issue by xixixao** [picnicss/picnic#7]
When I tap, not click, the trackpad, the animation doesn't trigger (the actual link behind the button still triggers).

**Comment by FranciscoP** [comment]
Any update here?

**Comment by FranciscoP** [comment]
No down status anymore since 3.0. Closed as invalid now.

**Comment by xixixao** [comment]
I guess the website isn't updated, but not having a down state is terrible UX.

**Comment by FranciscoP** [comment]
Sorry for the confussion. The change from 2.x to 3.x is flat style. There is pressed style now ("down state") which moves the button in the z direction, otherwise it would be bad UX as you point out.

What I meant is that the button doesn't translate in the y direction, as it did previously. The style has changed from the y and z pressed state to only z (darker color). The website *is* updated with these changes. If the issue continues with the new, completely different style please reopen the issue.
